# Generated by Django 4.1.7 on 2023-04-04 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0003_item_category_alter_item_name"),
        ("message", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagemodel",
            name="about_item",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="about_item",
                to="items.item",
            ),
            preserve_default=False,
        ),
    ]
